export const personalityTraits = [
    { id: 1, label: "Funny", value: "funny" },
    { id: 2, label: "Silly", value: "silly" },
    { id: 3, label: "Smart", value: "smart" },
    { id: 4, label: "Flirty", value: "flirty" },
    { id: 5, label: "Shy", value: "shy" },
    { id: 6, label: "Relaxed", value: "relaxed" },
    { id: 7, label: "Dominant", value: "dominant" },
    { id: 8, label: "Confident", value: "confident" },
    { id: 9, label: "Crazy", value: "crazy" },
    { id: 10, label: "Adventurous", value: "adventurous" },
    { id: 11, label: "Supportive", value: "supportive" },
    { id: 12, label: "Bitchy", value: "bitchy" },
    { id: 13, label: "Play Hard To Get", value: "play-hard-to-get" },
    { id: 14, label: "Emotionally Cold", value: "emotionally-cold" },
    { id: 15, label: "Open", value: "open" },
    { id: 16, label: "Optimistic", value: "optimistic" },
    { id: 17, label: "Pessimistic", value: "pessimistic" },
    { id: 18, label: "Proud", value: "proud" },
    { id: 19, label: "Naive", value: "naive" },
    { id: 20, label: "Playful", value: "playful" },
    { id: 21, label: "Smug", value: "smug" },
    { id: 22, label: "Enthusiastic", value: "enthusiastic" },
    { id: 23, label: "Messy", value: "messy" },
    { id: 24, label: "Lazy", value: "lazy" },
    { id: 25, label: "Innocent", value: "innocent" },
    { id: 26, label: "Possessive", value: "possessive" },
    { id: 27, label: "Elegant", value: "elegant" },
    { id: 28, label: "Chill", value: "chill" },
    { id: 29, label: "Serious", value: "serious" },
];
